# Auto-generated file containing combined cards_info dictionary
cards_info = \
{ 'Silver Tempest': {'code': 'swsh12', 'cards': []},
  'Phantasmal Flames': { 'code': 'me2',
                         'cards': [ { 'name': 'Mega Charizard X ex',
                                      'market': 542.46,
                                      'price_high': 2222.0,
                                      'printed_total': 94,
                                      'number': '125',
                                      'card_link': 'https://prices.pokemontcg.io/tcgplayer/me2-125',
                                      'pricecharting_url': 'https://pricecharting.com/game/pokemon-phantasmal-flames/mega-charizard-x-ex-125',
                                      'graded_prices': { 'ungraded': '$598.89',
                                                         'grade7': '-',
                                                         'grade8': '$510.00',
                                                         'grade9': '$870.00',
                                                         'grade95': '$1,087.50',
                                                         'grade10': '$2,190.26'},
                                      'image_url': 'https://images.pokemontcg.io/me2/125_hires.png'},
                                    { 'name': 'Mega Charizard X ex',
                                      'market': 391.14,
                                      'price_high': 99999.0,
                                      'printed_total': 94,
                                      'number': '130',
                                      'card_link': 'https://prices.pokemontcg.io/tcgplayer/me2-130',
                                      'pricecharting_url': 'https://pricecharting.com/game/pokemon-phantasmal-flames/mega-charizard-x-ex-130',
                                      'graded_prices': { 'ungraded': '$412.12',
                                                         'grade7': '-',
                                                         'grade8': '$382.51',
                                                         'grade9': '$637.13',
                                                         'grade95': '$850.00',
                                                         'grade10': '$3,100.00'},
                                      'image_url': 'https://images.pokemontcg.io/me2/130_hires.png'}]},
  'Prismatic Evolutions': { 'code': 'sv8pt5',
                            'cards': [ { 'name': 'Ceruledge ex',
                                         'market': 102.38,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '147',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-147',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/ceruledge-ex-147',
                                         'graded_prices': { 'ungraded': '$89.50',
                                                            'grade7': '-',
                                                            'grade8': '$87.63',
                                                            'grade9': '$100.00',
                                                            'grade95': '$148.18',
                                                            'grade10': '$302.86'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/147_hires.png'},
                                       { 'name': 'Flareon ex',
                                         'market': 161.13,
                                         'price_high': 9999.0,
                                         'printed_total': 131,
                                         'number': '146',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-146',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/flareon-ex-146',
                                         'graded_prices': { 'ungraded': '$139.09',
                                                            'grade7': '-',
                                                            'grade8': '$149.75',
                                                            'grade9': '$151.47',
                                                            'grade95': '$183.20',
                                                            'grade10': '$600.64'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/146_hires.png'},
                                       { 'name': 'Jolteon ex',
                                         'market': 153.76,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '153',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-153',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/jolteon-ex-153',
                                         'graded_prices': { 'ungraded': '$138.01',
                                                            'grade7': '-',
                                                            'grade8': '$135.50',
                                                            'grade9': '$158.20',
                                                            'grade95': '$174.00',
                                                            'grade10': '$495.68'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/153_hires.png'},
                                       { 'name': 'Glaceon ex',
                                         'market': 193.11,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '150',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-150',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/glaceon-ex-150',
                                         'graded_prices': { 'ungraded': '$182.50',
                                                            'grade7': '$128.00',
                                                            'grade8': '$159.64',
                                                            'grade9': '$163.70',
                                                            'grade95': '$219.25',
                                                            'grade10': '$577.33'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/150_hires.png'},
                                       { 'name': 'Vaporeon ex',
                                         'market': 192.28,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '149',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-149',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/vaporeon-ex-149',
                                         'graded_prices': { 'ungraded': '$186.21',
                                                            'grade7': '$149.25',
                                                            'grade8': '$170.00',
                                                            'grade9': '$194.23',
                                                            'grade95': '$400.00',
                                                            'grade10': '$916.71'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/149_hires.png'},
                                       { 'name': 'Espeon ex',
                                         'market': 201.73,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '155',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-155',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/espeon-ex-155',
                                         'graded_prices': { 'ungraded': '$193.07',
                                                            'grade7': '$180.00',
                                                            'grade8': '$198.75',
                                                            'grade9': '$200.00',
                                                            'grade95': '$340.00',
                                                            'grade10': '$828.50'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/155_hires.png'},
                                       { 'name': 'Sylveon ex',
                                         'market': 325.3,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '156',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-156',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/sylveon-ex-156',
                                         'graded_prices': { 'ungraded': '$311.50',
                                                            'grade7': '$250.61',
                                                            'grade8': '$290.63',
                                                            'grade9': '$310.00',
                                                            'grade95': '$390.65',
                                                            'grade10': '$1,079.54'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/156_hires.png'},
                                       { 'name': 'Roaring Moon ex',
                                         'market': 174.19,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '162',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-162',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/roaring-moon-ex-162',
                                         'graded_prices': { 'ungraded': '$164.79',
                                                            'grade7': '-',
                                                            'grade8': '$165.81',
                                                            'grade9': '$171.36',
                                                            'grade95': '$425.00',
                                                            'grade10': '$749.76'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/162_hires.png'},
                                       { 'name': 'Umbreon ex',
                                         'market': 1027.07,
                                         'price_high': 5000.0,
                                         'printed_total': 131,
                                         'number': '161',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-161',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/umbreon-ex-161',
                                         'graded_prices': { 'ungraded': '$925.64',
                                                            'grade7': '$870.00',
                                                            'grade8': '$890.00',
                                                            'grade9': '$980.00',
                                                            'grade95': '$1,597.50',
                                                            'grade10': '$3,191.42'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/161_hires.png'},
                                       { 'name': 'Eevee ex',
                                         'market': 112.87,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '167',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-167',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/eevee-ex-167',
                                         'graded_prices': { 'ungraded': '$109.22',
                                                            'grade7': '-',
                                                            'grade8': '$90.50',
                                                            'grade9': '$117.01',
                                                            'grade95': '$180.84',
                                                            'grade10': '$565.00'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/167_hires.png'}]},
  'Black Bolt': { 'code': 'zsv10pt5',
                  'cards': [ { 'name': 'Seismitoad',
                               'market': 152.89,
                               'price_high': 450.0,
                               'printed_total': 86,
                               'number': '105',
                               'card_link': 'https://prices.pokemontcg.io/tcgplayer/zsv10pt5-105',
                               'pricecharting_url': 'https://pricecharting.com/game/pokemon-black-bolt/seismitoad-105',
                               'graded_prices': { 'ungraded': '$150.37',
                                                  'grade7': '$97.00',
                                                  'grade8': '$121.04',
                                                  'grade9': '$146.59',
                                                  'grade95': '$240.00',
                                                  'grade10': '$756.10'},
                               'image_url': 'https://images.pokemontcg.io/zsv10pt5/105_hires.png'}]},
  'Crown Zenith Galarian Gallery': {'code': 'swsh12pt5gg', 'cards': []},
  'Chilling Reign': {'code': 'swsh6', 'cards': []},
  'Twilight Masquerade': {'code': 'sv6', 'cards': []},
  'Lost Origin': { 'code': 'swsh11',
                   'cards': [ { 'name': 'Giratina V',
                                'market': 580.63,
                                'price_high': 1000.0,
                                'printed_total': 196,
                                'number': '186',
                                'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh11-186',
                                'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-origin/giratina-v-186',
                                'graded_prices': { 'ungraded': '$492.54',
                                                   'grade7': '$434.07',
                                                   'grade8': '$518.27',
                                                   'grade9': '$625.99',
                                                   'grade95': '$1,208.23',
                                                   'grade10': '$1,919.13'},
                                'image_url': 'https://images.pokemontcg.io/swsh11/186_hires.png'}]},
  'Battle Styles': { 'code': 'swsh5',
                     'cards': [ { 'name': 'Tyranitar V',
                                  'market': 206.76,
                                  'price_high': 1000.0,
                                  'printed_total': 163,
                                  'number': '155',
                                  'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh5-155',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-battle-styles/tyranitar-v-155',
                                  'graded_prices': { 'ungraded': '$181.88',
                                                     'grade7': '$98.35',
                                                     'grade8': '$177.55',
                                                     'grade9': '$219.09',
                                                     'grade95': '$320.25',
                                                     'grade10': '$660.00'},
                                  'image_url': 'https://images.pokemontcg.io/swsh5/155_hires.png'}]},
  'Mega Evolution': { 'code': 'me1',
                      'cards': [ { 'name': 'Mega Absol ex',
                                   'market': 81.84,
                                   'price_high': 999.0,
                                   'printed_total': 132,
                                   'number': '180',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/me1-180',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-absol-ex-180',
                                   'graded_prices': { 'ungraded': '$70.61',
                                                      'grade7': '-',
                                                      'grade8': '$101.20',
                                                      'grade9': '$111.00',
                                                      'grade95': '$122.00',
                                                      'grade10': '$275.26'},
                                   'image_url': 'https://images.pokemontcg.io/me1/180_hires.png'},
                                 { 'name': 'Mega Latias ex',
                                   'market': 95.54,
                                   'price_high': 999.0,
                                   'printed_total': 132,
                                   'number': '181',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/me1-181',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-latias-ex-181',
                                   'graded_prices': { 'ungraded': '$104.41',
                                                      'grade7': '-',
                                                      'grade8': '-',
                                                      'grade9': '$141.00',
                                                      'grade95': '$155.00',
                                                      'grade10': '$362.50'},
                                   'image_url': 'https://images.pokemontcg.io/me1/181_hires.png'},
                                 { 'name': 'Mega Venusaur ex',
                                   'market': 146.37,
                                   'price_high': 999.0,
                                   'printed_total': 132,
                                   'number': '177',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/me1-177',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-venusaur-ex-177',
                                   'graded_prices': { 'ungraded': '$133.99',
                                                      'grade7': '-',
                                                      'grade8': '$170.00',
                                                      'grade9': '$187.00',
                                                      'grade95': '$197.50',
                                                      'grade10': '$464.36'},
                                   'image_url': 'https://images.pokemontcg.io/me1/177_hires.png'}]},
  'Destined Rivals': { 'code': 'sv10',
                       'cards': [ { 'name': "Team Rocket's Moltres ex",
                                    'market': 123.77,
                                    'price_high': 300.0,
                                    'printed_total': 182,
                                    'number': '229',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv10-229',
                                    'pricecharting_url': "https://pricecharting.com/game/pokemon-destined-rivals/team-rocket's-moltres-ex-229",
                                    'graded_prices': { 'ungraded': '$121.00',
                                                       'grade7': '$110.50',
                                                       'grade8': '$129.22',
                                                       'grade9': '$142.00',
                                                       'grade95': '$256.48',
                                                       'grade10': '$344.95'},
                                    'image_url': 'https://images.pokemontcg.io/sv10/229_hires.png'},
                                  { 'name': "Team Rocket's Nidoking ex",
                                    'market': 101.04,
                                    'price_high': 400.0,
                                    'printed_total': 182,
                                    'number': '233',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv10-233',
                                    'pricecharting_url': "https://pricecharting.com/game/pokemon-destined-rivals/team-rocket's-nidoking-ex-233",
                                    'graded_prices': { 'ungraded': '$102.54',
                                                       'grade7': '$76.00',
                                                       'grade8': '$94.79',
                                                       'grade9': '$113.93',
                                                       'grade95': '$125.00',
                                                       'grade10': '$303.00'},
                                    'image_url': 'https://images.pokemontcg.io/sv10/233_hires.png'}]},
  'Paradox Rift': {'code': 'sv4', 'cards': []},
  'Darkness Ablaze': {'code': 'swsh3', 'cards': []},
  '151': { 'code': 'sv3pt5',
           'cards': [ { 'name': 'Charizard ex',
                        'market': 238.41,
                        'price_high': 900.0,
                        'printed_total': 165,
                        'number': '199',
                        'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv3pt5-199',
                        'pricecharting_url': 'https://pricecharting.com/game/pokemon-scarlet-&-violet-151/charizard-ex-199',
                        'graded_prices': { 'ungraded': '$221.32',
                                           'grade7': '$171.48',
                                           'grade8': '$223.00',
                                           'grade9': '$250.00',
                                           'grade95': '$350.00',
                                           'grade10': '$962.00'},
                        'image_url': 'https://images.pokemontcg.io/sv3pt5/199_hires.png'}]},
  'White Flare': {'code': 'rsv10pt5', 'cards': []},
  'Crown Zenith': {'code': 'swsh12pt5', 'cards': []},
  'Rebel Clash': {'code': 'swsh2', 'cards': []},
  'Fusion Strike': { 'code': 'swsh8',
                     'cards': [ { 'name': 'Mew V',
                                  'market': 94.56,
                                  'price_high': 500.0,
                                  'printed_total': 264,
                                  'number': '251',
                                  'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh8-251',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-fusion-strike/mew-v-251',
                                  'graded_prices': { 'ungraded': '$80.50',
                                                     'grade7': '$40.64',
                                                     'grade8': '$77.86',
                                                     'grade9': '$95.13',
                                                     'grade95': '$147.68',
                                                     'grade10': '$295.03'},
                                  'image_url': 'https://images.pokemontcg.io/swsh8/251_hires.png'}]},
  'Shining Fates': {'code': 'swsh45', 'cards': []},
  'Surging Sparks': { 'code': 'sv8',
                      'cards': [ { 'name': 'Milotic ex',
                                   'market': 95.79,
                                   'price_high': 199.95,
                                   'printed_total': 191,
                                   'number': '237',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8-237',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-surging-sparks/milotic-ex-237',
                                   'graded_prices': { 'ungraded': '$93.56',
                                                      'grade7': '$68.00',
                                                      'grade8': '$85.50',
                                                      'grade9': '$89.99',
                                                      'grade95': '$158.75',
                                                      'grade10': '$282.04'},
                                   'image_url': 'https://images.pokemontcg.io/sv8/237_hires.png'},
                                 { 'name': 'Pikachu ex',
                                   'market': 285.96,
                                   'price_high': 868.0,
                                   'printed_total': 191,
                                   'number': '238',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8-238',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-surging-sparks/pikachu-ex-238',
                                   'graded_prices': { 'ungraded': '$283.84',
                                                      'grade7': '$197.00',
                                                      'grade8': '$246.60',
                                                      'grade9': '$269.11',
                                                      'grade95': '$406.14',
                                                      'grade10': '$900.00'},
                                   'image_url': 'https://images.pokemontcg.io/sv8/238_hires.png'},
                                 { 'name': 'Latias ex',
                                   'market': 168.94,
                                   'price_high': 370.0,
                                   'printed_total': 191,
                                   'number': '239',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8-239',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-surging-sparks/latias-ex-239',
                                   'graded_prices': { 'ungraded': '$145.00',
                                                      'grade7': '$123.00',
                                                      'grade8': '$153.64',
                                                      'grade9': '$169.00',
                                                      'grade95': '$240.68',
                                                      'grade10': '$565.00'},
                                   'image_url': 'https://images.pokemontcg.io/sv8/239_hires.png'}]},
  "Champion's Path": {'code': 'swsh35', 'cards': []},
  'Evolving Skies': {'code': 'swsh7', 'cards': []},
  'Paldea Evolved': { 'code': 'sv2',
                      'cards': [ { 'name': 'Magikarp',
                                   'market': 251.89,
                                   'price_high': 1200.0,
                                   'printed_total': 193,
                                   'number': '203',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv2-203',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-paldea-evolved/magikarp-203',
                                   'graded_prices': { 'ungraded': '$226.53',
                                                      'grade7': '$185.00',
                                                      'grade8': '$232.87',
                                                      'grade9': '$292.50',
                                                      'grade95': '$585.31',
                                                      'grade10': '$1,825.00'},
                                   'image_url': 'https://images.pokemontcg.io/sv2/203_hires.png'}]},
  'Obsidian Flames': {'code': 'sv3', 'cards': []},
  'Astral Radiance': { 'code': 'swsh10',
                       'cards': [ { 'name': 'Starmie V',
                                    'market': 96.29,
                                    'price_high': 249.0,
                                    'printed_total': 30,
                                    'number': 'TG13',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh10tg-TG13',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-astral-radiance/starmie-v-TG13',
                                    'graded_prices': { 'ungraded': '$91.02',
                                                       'grade7': '$77.02',
                                                       'grade8': '$89.00',
                                                       'grade9': '$100.00',
                                                       'grade95': '$126.94',
                                                       'grade10': '$279.53'},
                                    'image_url': 'https://images.pokemontcg.io/swsh10tg/TG13_hires.png'}]},
  'Vivid Voltage': {'code': 'swsh4', 'cards': []},
  'Paldean Fates': { 'code': 'sv4pt5',
                     'cards': [ { 'name': 'Mew ex',
                                  'market': 515.61,
                                  'price_high': 10000.0,
                                  'printed_total': 91,
                                  'number': '232',
                                  'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv4pt5-232',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-paldean-fates/mew-ex-232',
                                  'graded_prices': { 'ungraded': '$482.94',
                                                     'grade7': '$425.00',
                                                     'grade8': '$434.23',
                                                     'grade9': '$514.72',
                                                     'grade95': '$871.99',
                                                     'grade10': '$1,475.50'},
                                  'image_url': 'https://images.pokemontcg.io/sv4pt5/232_hires.png'}]},
  'Journey Together': { 'code': 'sv9',
                        'cards': [ { 'name': "Lillie's Clefairy ex",
                                     'market': 137.08,
                                     'price_high': 375.0,
                                     'printed_total': 159,
                                     'number': '184',
                                     'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv9-184',
                                     'pricecharting_url': "https://pricecharting.com/game/pokemon-journey-together/lillie's-clefairy-ex-184",
                                     'graded_prices': { 'ungraded': '$133.33',
                                                        'grade7': '$123.88',
                                                        'grade8': '$129.41',
                                                        'grade9': '$145.00',
                                                        'grade95': '$194.85',
                                                        'grade10': '$450.00'},
                                     'image_url': 'https://images.pokemontcg.io/sv9/184_hires.png'}]}}
