# Auto-generated file containing combined cards_info dictionary
cards_info = \
{ 'Silver Tempest': {'code': 'swsh12', 'cards': []},
  'Hidden Fates': {'code': 'sm115', 'cards': []},
  'Ultra Prism': { 'code': 'sm5',
                   'cards': [ { 'name': 'Leafeon GX',
                                'market': 86.38,
                                'price_high': 699.95,
                                'printed_total': 156,
                                'number': '157',
                                'card_link': 'https://www.tcgplayer.com/product/157773',
                                'pricecharting_url': 'https://pricecharting.com/game/pokemon-ultra-prism/leafeon-gx-157',
                                'graded_prices': { 'ungraded': '$59.45',
                                                   'grade7': '$42.35',
                                                   'grade8': '$49.99',
                                                   'grade9': '$88.50',
                                                   'grade95': '$97.00',
                                                   'grade10': '$242.30'},
                                'image_url': 'https://assets.tcgdex.net/en/sm/sm5/157/high.png'}]},
  'Phantasmal Flames': {'code': 'me02', 'cards': []},
  'Prismatic Evolutions': {'code': 'sv08.5', 'cards': []},
  'Crimson Invasion': {'code': 'sm4', 'cards': []},
  'Team Up': { 'code': 'sm9',
               'cards': [ { 'name': 'Gengar & Mimikyu GX',
                            'market': 241.86,
                            'price_high': 499,
                            'printed_total': 181,
                            'number': '53',
                            'card_link': 'https://www.tcgplayer.com/product/183828',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/gengar-&-mimikyu-gx-53',
                            'graded_prices': { 'ungraded': '$192.29',
                                               'grade7': '$199.60',
                                               'grade8': '$213.75',
                                               'grade9': '$300.00',
                                               'grade95': '$410.65',
                                               'grade10': '$1,158.36'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/53/high.png'},
                          { 'name': 'Magikarp & Wailord GX',
                            'market': 97.08,
                            'price_high': 133.47,
                            'printed_total': 181,
                            'number': '160',
                            'card_link': 'https://www.tcgplayer.com/product/183963',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/magikarp-&-wailord-gx-160',
                            'graded_prices': { 'ungraded': '$93.73',
                                               'grade7': '$83.48',
                                               'grade8': '$84.00',
                                               'grade9': '$129.00',
                                               'grade95': '$142.00',
                                               'grade10': '$385.00'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/160/high.png'},
                          { 'name': 'Pikachu & Zekrom GX',
                            'market': 142.98,
                            'price_high': 445,
                            'printed_total': 181,
                            'number': '162',
                            'card_link': 'https://www.tcgplayer.com/product/183805',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/pikachu-&-zekrom-gx-162',
                            'graded_prices': { 'ungraded': '$107.50',
                                               'grade7': '$80.81',
                                               'grade8': '$87.77',
                                               'grade9': '$136.39',
                                               'grade95': '$150.00',
                                               'grade10': '$397.49'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/162/high.png'},
                          { 'name': 'Gengar & Mimikyu GX',
                            'market': 285.23,
                            'price_high': 329.98,
                            'printed_total': 181,
                            'number': '164',
                            'card_link': 'https://www.tcgplayer.com/product/183829',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/gengar-&-mimikyu-gx-164',
                            'graded_prices': { 'ungraded': '$216.57',
                                               'grade7': '$61.26',
                                               'grade8': '$237.50',
                                               'grade9': '$320.00',
                                               'grade95': '$477.35',
                                               'grade10': '$867.40'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/164/high.png'},
                          { 'name': 'Gengar & Mimikyu GX',
                            'market': 1234.61,
                            'price_high': 1675,
                            'printed_total': 181,
                            'number': '165',
                            'card_link': 'https://www.tcgplayer.com/product/183830',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/gengar-&-mimikyu-gx-165',
                            'graded_prices': { 'ungraded': '$850.00',
                                               'grade7': '$750.00',
                                               'grade8': '$1,050.00',
                                               'grade9': '$1,307.24',
                                               'grade95': '$2,500.00',
                                               'grade10': '$3,900.00'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/165/high.png'},
                          { 'name': 'Latias & Latios GX',
                            'market': 91.34,
                            'price_high': 149.99,
                            'printed_total': 181,
                            'number': '169',
                            'card_link': 'https://www.tcgplayer.com/product/183898',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/latias-&-latios-gx-169',
                            'graded_prices': { 'ungraded': '$85.82',
                                               'grade7': '-',
                                               'grade8': '$91.43',
                                               'grade9': '$103.24',
                                               'grade95': '$119.99',
                                               'grade10': '$379.20'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/169/high.png'},
                          { 'name': 'Latias & Latios GX',
                            'market': 2682.47,
                            'price_high': 2942.11,
                            'printed_total': 181,
                            'number': '170',
                            'card_link': 'https://www.tcgplayer.com/product/183899',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/latias-&-latios-gx-170',
                            'graded_prices': { 'ungraded': '$1,869.53',
                                               'grade7': '$1,856.00',
                                               'grade8': '$2,286.84',
                                               'grade9': '$3,100.00',
                                               'grade95': '$5,600.00',
                                               'grade10': '$9,400.00'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/170/high.png'},
                          { 'name': 'Magikarp & Wailord GX',
                            'market': 116.99,
                            'price_high': 329.95,
                            'printed_total': 181,
                            'number': '183',
                            'card_link': 'https://www.tcgplayer.com/product/183965',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/magikarp-&-wailord-gx-183',
                            'graded_prices': { 'ungraded': '$102.57',
                                               'grade7': '$65.00',
                                               'grade8': '$76.95',
                                               'grade9': '$122.50',
                                               'grade95': '$135.00',
                                               'grade10': '$409.99'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/183/high.png'},
                          { 'name': 'Pikachu & Zekrom GX',
                            'market': 214.33,
                            'price_high': 499.95,
                            'printed_total': 181,
                            'number': '184',
                            'card_link': 'https://www.tcgplayer.com/product/183806',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/pikachu-&-zekrom-gx-184',
                            'graded_prices': { 'ungraded': '$100.27',
                                               'grade7': '$95.00',
                                               'grade8': '$122.50',
                                               'grade9': '$180.00',
                                               'grade95': '$198.00',
                                               'grade10': '$629.60'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/184/high.png'},
                          { 'name': 'Gengar & Mimikyu GX',
                            'market': 332.16,
                            'price_high': 399,
                            'printed_total': 181,
                            'number': '186',
                            'card_link': 'https://www.tcgplayer.com/product/183831',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/gengar-&-mimikyu-gx-186',
                            'graded_prices': { 'ungraded': '$305.43',
                                               'grade7': '$108.00',
                                               'grade8': '$231.25',
                                               'grade9': '$341.97',
                                               'grade95': '$395.29',
                                               'grade10': '$1,054.93'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/186/high.png'},
                          { 'name': 'Latias & Latios GX',
                            'market': 177.67,
                            'price_high': 290.19,
                            'printed_total': 181,
                            'number': '190',
                            'card_link': 'https://www.tcgplayer.com/product/183900',
                            'pricecharting_url': 'https://pricecharting.com/game/pokemon-team-up/latias-&-latios-gx-190',
                            'graded_prices': { 'ungraded': '$132.01',
                                               'grade7': '$38.00',
                                               'grade8': '$122.45',
                                               'grade9': '$152.50',
                                               'grade95': '$177.50',
                                               'grade10': '$635.00'},
                            'image_url': 'https://assets.tcgdex.net/en/sm/sm9/190/high.png'}]},
  'Black Bolt': {'code': 'sv10.5b', 'cards': []},
  'Crown Zenith Galarian Gallery': {'code': 'swsh12pt5gg', 'cards': []},
  'Chilling Reign': {'code': 'swsh6', 'cards': []},
  'Twilight Masquerade': {'code': 'sv06', 'cards': []},
  'Lost Origin': { 'code': 'swsh11',
                   'cards': [ { 'name': 'Giratina V',
                                'market': 658.24,
                                'price_high': 1500,
                                'printed_total': 196,
                                'number': '186',
                                'card_link': 'https://www.tcgplayer.com/product/284137',
                                'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-origin/giratina-v-186',
                                'graded_prices': { 'ungraded': '$569.58',
                                                   'grade7': '$460.00',
                                                   'grade8': '$534.84',
                                                   'grade9': '$661.00',
                                                   'grade95': '$1,100.00',
                                                   'grade10': '$2,025.17'},
                                'image_url': 'https://assets.tcgdex.net/en/swsh/swsh11/186/high.png'}]},
  'Battle Styles': { 'code': 'swsh5',
                     'cards': [ { 'name': 'Tyranitar V',
                                  'market': 200.31,
                                  'price_high': 1000,
                                  'printed_total': 163,
                                  'number': '155',
                                  'card_link': 'https://www.tcgplayer.com/product/234060',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-battle-styles/tyranitar-v-155',
                                  'graded_prices': { 'ungraded': '$182.24',
                                                     'grade7': '$87.50',
                                                     'grade8': '$198.51',
                                                     'grade9': '$209.11',
                                                     'grade95': '$335.00',
                                                     'grade10': '$627.50'},
                                  'image_url': 'https://assets.tcgdex.net/en/swsh/swsh5/155/high.png'}]},
  'Shining Legends': { 'code': 'sm35',
                       'cards': [ { 'name': 'Shining Mew',
                                    'market': 82.3,
                                    'price_high': 149.98,
                                    'printed_total': 73,
                                    'number': '40',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sm35-40',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-shining-legends/shining-mew-40',
                                    'graded_prices': { 'ungraded': '$75.00',
                                                       'grade7': '$66.00',
                                                       'grade8': '$80.00',
                                                       'grade9': '$117.88',
                                                       'grade95': '$171.13',
                                                       'grade10': '$468.35'},
                                    'image_url': 'https://images.pokemontcg.io/sm35/40_hires.png'},
                                  { 'name': 'Mewtwo-GX',
                                    'market': 519.72,
                                    'price_high': 699.99,
                                    'printed_total': 73,
                                    'number': '78',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sm35-78',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-shining-legends/mewtwo-gx-78',
                                    'graded_prices': { 'ungraded': '$330.57',
                                                       'grade7': '$420.00',
                                                       'grade8': '$502.36',
                                                       'grade9': '$834.07',
                                                       'grade95': '$2,550.00',
                                                       'grade10': '$4,334.95'},
                                    'image_url': 'https://images.pokemontcg.io/sm35/78_hires.png'}]},
  'Mega Evolution': { 'code': 'me01',
                      'cards': [ { 'name': 'Mega Gardevoir ex',
                                   'market': 234.44,
                                   'price_high': 1199.99,
                                   'printed_total': 132,
                                   'number': '187',
                                   'card_link': 'https://www.tcgplayer.com/product/654526',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-gardevoir-ex-187',
                                   'graded_prices': { 'ungraded': '$236.05',
                                                      'grade7': '$160.00',
                                                      'grade8': '$200.00',
                                                      'grade9': '$249.97',
                                                      'grade95': '$355.00',
                                                      'grade10': '$675.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/me/me01/187/high.png'},
                                 { 'name': 'Mega Lucario ex',
                                   'market': 289.15,
                                   'price_high': 999,
                                   'printed_total': 132,
                                   'number': '188',
                                   'card_link': 'https://www.tcgplayer.com/product/654527',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-lucario-ex-188',
                                   'graded_prices': { 'ungraded': '$288.69',
                                                      'grade7': '$180.00',
                                                      'grade8': '$266.22',
                                                      'grade9': '$295.00',
                                                      'grade95': '$420.50',
                                                      'grade10': '$925.51'},
                                   'image_url': 'https://assets.tcgdex.net/en/me/me01/188/high.png'}]},
  'Destined Rivals': {'code': 'sv10', 'cards': []},
  'Unbroken Bonds': { 'code': 'sm10',
                      'cards': [ { 'name': 'Reshiram & Charizard GX',
                                   'market': 85.79,
                                   'price_high': 249.95,
                                   'printed_total': 214,
                                   'number': '194',
                                   'card_link': 'https://www.tcgplayer.com/product/189318',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-unbroken-bonds/reshiram-&-charizard-gx-194',
                                   'graded_prices': { 'ungraded': '$66.87',
                                                      'grade7': '$49.28',
                                                      'grade8': '$49.99',
                                                      'grade9': '$87.50',
                                                      'grade95': '$131.43',
                                                      'grade10': '$300.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm10/194/high.png'},
                                 { 'name': 'Greninja & Zoroark GX',
                                   'market': 283.81,
                                   'price_high': 499.95,
                                   'printed_total': 214,
                                   'number': '201',
                                   'card_link': 'https://www.tcgplayer.com/product/189310',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-unbroken-bonds/greninja-&-zoroark-gx-201',
                                   'graded_prices': { 'ungraded': '$244.01',
                                                      'grade7': '$72.90',
                                                      'grade8': '$226.11',
                                                      'grade9': '$327.65',
                                                      'grade95': '$380.09',
                                                      'grade10': '$833.50'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm10/201/high.png'},
                                 { 'name': 'Gardevoir & Sylveon GX',
                                   'market': 535.55,
                                   'price_high': 999.99,
                                   'printed_total': 214,
                                   'number': '205',
                                   'card_link': 'https://www.tcgplayer.com/product/189316',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-unbroken-bonds/gardevoir-&-sylveon-gx-205',
                                   'graded_prices': { 'ungraded': '$446.01',
                                                      'grade7': '$499.99',
                                                      'grade8': '$528.99',
                                                      'grade9': '$637.50',
                                                      'grade95': '$743.38',
                                                      'grade10': '$1,562.93'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm10/205/high.png'},
                                 { 'name': 'Blastoise GX',
                                   'market': 100.51,
                                   'price_high': 115.59,
                                   'printed_total': 214,
                                   'number': '218',
                                   'card_link': 'https://www.tcgplayer.com/product/189100',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-unbroken-bonds/blastoise-gx-218',
                                   'graded_prices': { 'ungraded': '$95.26',
                                                      'grade7': '$57.47',
                                                      'grade8': '$77.80',
                                                      'grade9': '$92.26',
                                                      'grade95': '$104.75',
                                                      'grade10': '$359.70'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm10/218/high.png'}]},
  'Paradox Rift': {'code': 'sv4', 'cards': []},
  'Darkness Ablaze': {'code': 'swsh3', 'cards': []},
  '151': {'code': 'sv03.5', 'cards': []},
  'White Flare': {'code': 'rsv10pt5', 'cards': []},
  'Crown Zenith': {'code': 'swsh12.5', 'cards': []},
  'Celestial Storm': { 'code': 'sm7',
                       'cards': [ { 'name': 'Rayquaza-GX',
                                    'market': 234.87,
                                    'price_high': 699.99,
                                    'printed_total': 168,
                                    'number': '177',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sm7-177',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-celestial-storm/rayquaza-gx-177',
                                    'graded_prices': { 'ungraded': '$169.06',
                                                       'grade7': '$120.00',
                                                       'grade8': '$144.67',
                                                       'grade9': '$202.92',
                                                       'grade95': '$289.14',
                                                       'grade10': '$795.50'},
                                    'image_url': 'https://images.pokemontcg.io/sm7/177_hires.png'}]},
  'Sun & Moon': { 'code': 'sm1',
                  'cards': [ { 'name': 'Umbreon GX',
                               'market': 104.11,
                               'price_high': 250,
                               'printed_total': 149,
                               'number': '154',
                               'card_link': 'https://www.tcgplayer.com/product/127193',
                               'pricecharting_url': 'https://pricecharting.com/game/pokemon-sun-&-moon/umbreon-gx-154',
                               'graded_prices': { 'ungraded': '$64.16',
                                                  'grade7': '$47.91',
                                                  'grade8': '$75.00',
                                                  'grade9': '$117.54',
                                                  'grade95': '$140.00',
                                                  'grade10': '$670.00'},
                               'image_url': 'https://assets.tcgdex.net/en/sm/sm1/154/high.png'}]},
  'Rebel Clash': {'code': 'swsh2', 'cards': []},
  'Fusion Strike': { 'code': 'swsh8',
                     'cards': [ { 'name': 'Mew V',
                                  'market': 87.85,
                                  'price_high': 500,
                                  'printed_total': 264,
                                  'number': '251',
                                  'card_link': 'https://www.tcgplayer.com/product/253147',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-fusion-strike/mew-v-251',
                                  'graded_prices': { 'ungraded': '$85.00',
                                                     'grade7': '$40.03',
                                                     'grade8': '$82.00',
                                                     'grade9': '$95.00',
                                                     'grade95': '$151.87',
                                                     'grade10': '$322.50'},
                                  'image_url': 'https://assets.tcgdex.net/en/swsh/swsh8/251/high.png'}]},
  'Lost Thunder': { 'code': 'sm8',
                    'cards': [ { 'name': 'Lugia GX',
                                 'market': 101.01,
                                 'price_high': 150,
                                 'printed_total': 214,
                                 'number': '207',
                                 'card_link': 'https://www.tcgplayer.com/product/178981',
                                 'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-thunder/lugia-gx-207',
                                 'graded_prices': { 'ungraded': '$98.73',
                                                    'grade7': '$77.00',
                                                    'grade8': '$96.56',
                                                    'grade9': '$189.77',
                                                    'grade95': '$219.99',
                                                    'grade10': '$802.50'},
                                 'image_url': 'https://assets.tcgdex.net/en/sm/sm8/207/high.png'},
                               { 'name': 'Suicune GX',
                                 'market': 87.16,
                                 'price_high': 128.13,
                                 'printed_total': 214,
                                 'number': '220',
                                 'card_link': 'https://www.tcgplayer.com/product/178869',
                                 'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-thunder/suicune-gx-220',
                                 'graded_prices': { 'ungraded': '$74.86',
                                                    'grade7': '$37.00',
                                                    'grade8': '$45.86',
                                                    'grade9': '$86.04',
                                                    'grade95': '$95.00',
                                                    'grade10': '$381.51'},
                                 'image_url': 'https://assets.tcgdex.net/en/sm/sm8/220/high.png'},
                               { 'name': 'Tyranitar GX',
                                 'market': 102.4,
                                 'price_high': 200,
                                 'printed_total': 214,
                                 'number': '223',
                                 'card_link': 'https://www.tcgplayer.com/product/178936',
                                 'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-thunder/tyranitar-gx-223',
                                 'graded_prices': { 'ungraded': '$50.60',
                                                    'grade7': '$28.00',
                                                    'grade8': '$52.13',
                                                    'grade9': '$93.99',
                                                    'grade95': '$103.00',
                                                    'grade10': '$370.00'},
                                 'image_url': 'https://assets.tcgdex.net/en/sm/sm8/223/high.png'},
                               { 'name': 'Mimikyu GX',
                                 'market': 197.83,
                                 'price_high': 354.37,
                                 'printed_total': 214,
                                 'number': '226',
                                 'card_link': 'https://www.tcgplayer.com/product/178970',
                                 'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-thunder/mimikyu-gx-226',
                                 'graded_prices': { 'ungraded': '$195.00',
                                                    'grade7': '$114.25',
                                                    'grade8': '$134.99',
                                                    'grade9': '$227.85',
                                                    'grade95': '$251.00',
                                                    'grade10': '$710.00'},
                                 'image_url': 'https://assets.tcgdex.net/en/sm/sm8/226/high.png'},
                               { 'name': 'Lugia GX',
                                 'market': 216.27,
                                 'price_high': 259.99,
                                 'printed_total': 214,
                                 'number': '227',
                                 'card_link': 'https://www.tcgplayer.com/product/178982',
                                 'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-thunder/lugia-gx-227',
                                 'graded_prices': { 'ungraded': '$208.30',
                                                    'grade7': '$90.00',
                                                    'grade8': '$226.26',
                                                    'grade9': '$250.00',
                                                    'grade95': '$367.57',
                                                    'grade10': '$1,010.60'},
                                 'image_url': 'https://assets.tcgdex.net/en/sm/sm8/227/high.png'}]},
  'Cosmic Eclipse': { 'code': 'sm12',
                      'cards': [ { 'name': 'Vileplume GX',
                                   'market': 104.9,
                                   'price_high': 249.99,
                                   'printed_total': 236,
                                   'number': '211',
                                   'card_link': 'https://www.tcgplayer.com/product/201331',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/vileplume-gx-211',
                                   'graded_prices': { 'ungraded': '$100.00',
                                                      'grade7': '$29.63',
                                                      'grade8': '$66.50',
                                                      'grade9': '$102.00',
                                                      'grade95': '$112.00',
                                                      'grade10': '$365.48'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/211/high.png'},
                                 { 'name': 'Blastoise & Piplup GX',
                                   'market': 363.36,
                                   'price_high': 1000,
                                   'printed_total': 236,
                                   'number': '215',
                                   'card_link': 'https://www.tcgplayer.com/product/201334',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/blastoise-&-piplup-gx-215',
                                   'graded_prices': { 'ungraded': '$275.50',
                                                      'grade7': '$162.50',
                                                      'grade8': '$274.50',
                                                      'grade9': '$378.99',
                                                      'grade95': '$500.00',
                                                      'grade10': '$1,480.45'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/215/high.png'},
                                 { 'name': 'Solgaleo & Lunala GX',
                                   'market': 327.25,
                                   'price_high': 534.46,
                                   'printed_total': 236,
                                   'number': '216',
                                   'card_link': 'https://www.tcgplayer.com/product/201250',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/solgaleo-&-lunala-gx-216',
                                   'graded_prices': { 'ungraded': '$249.44',
                                                      'grade7': '$257.86',
                                                      'grade8': '$266.00',
                                                      'grade9': '$344.99',
                                                      'grade95': '$379.00',
                                                      'grade10': '$1,155.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/216/high.png'},
                                 { 'name': 'Arceus & Dialga & Palkia GX',
                                   'market': 458.21,
                                   'price_high': 599.75,
                                   'printed_total': 236,
                                   'number': '221',
                                   'card_link': 'https://www.tcgplayer.com/product/201338',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/arceus-&-dialga-&-palkia-gx-221',
                                   'graded_prices': { 'ungraded': '$263.29',
                                                      'grade7': '$196.25',
                                                      'grade8': '$337.50',
                                                      'grade9': '$461.65',
                                                      'grade95': '$508.00',
                                                      'grade10': '$1,800.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/221/high.png'},
                                 { 'name': 'Reshiram & Zekrom GX',
                                   'market': 424.08,
                                   'price_high': 669.95,
                                   'printed_total': 236,
                                   'number': '222',
                                   'card_link': 'https://www.tcgplayer.com/product/201339',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/reshiram-&-zekrom-gx-222',
                                   'graded_prices': { 'ungraded': '$325.00',
                                                      'grade7': '$297.50',
                                                      'grade8': '$349.50',
                                                      'grade9': '$399.99',
                                                      'grade95': '$440.00',
                                                      'grade10': '$1,391.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/222/high.png'},
                                 { 'name': 'Naganadel & Guzzlord GX',
                                   'market': 104.12,
                                   'price_high': 250,
                                   'printed_total': 236,
                                   'number': '224',
                                   'card_link': 'https://www.tcgplayer.com/product/201341',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/naganadel-&-guzzlord-gx-224',
                                   'graded_prices': { 'ungraded': '$94.01',
                                                      'grade7': '$37.21',
                                                      'grade8': '$66.00',
                                                      'grade9': '$103.32',
                                                      'grade95': '$114.00',
                                                      'grade10': '$325.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/224/high.png'},
                                 { 'name': 'Mega Lopunny & Jigglypuff GX',
                                   'market': 227.55,
                                   'price_high': 323.08,
                                   'printed_total': 236,
                                   'number': '226',
                                   'card_link': 'https://www.tcgplayer.com/product/201286',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/mega-lopunny-&-jigglypuff-gx-226',
                                   'graded_prices': { 'ungraded': '$193.16',
                                                      'grade7': '$61.00',
                                                      'grade8': '$163.00',
                                                      'grade9': '$221.98',
                                                      'grade95': '$244.00',
                                                      'grade10': '$757.67'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/226/high.png'},
                                 { 'name': 'Pikachu',
                                   'market': 118.1,
                                   'price_high': 300,
                                   'printed_total': 236,
                                   'number': '241',
                                   'card_link': 'https://www.tcgplayer.com/product/201352',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/pikachu-241',
                                   'graded_prices': { 'ungraded': '$99.86',
                                                      'grade7': '$86.87',
                                                      'grade8': '$110.00',
                                                      'grade9': '$152.75',
                                                      'grade95': '$200.48',
                                                      'grade10': '$829.50'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/241/high.png'},
                                 { 'name': 'Blastoise & Piplup GX',
                                   'market': 87.48,
                                   'price_high': 139.7,
                                   'printed_total': 236,
                                   'number': '253',
                                   'card_link': 'https://www.tcgplayer.com/product/201612',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-cosmic-eclipse/blastoise-&-piplup-gx-253',
                                   'graded_prices': { 'ungraded': '$84.81',
                                                      'grade7': '$59.67',
                                                      'grade8': '$69.99',
                                                      'grade9': '$89.35',
                                                      'grade95': '$98.00',
                                                      'grade10': '$305.00'},
                                   'image_url': 'https://assets.tcgdex.net/en/sm/sm12/253/high.png'}]},
  'Shining Fates': {'code': 'swsh45', 'cards': []},
  'Surging Sparks': {'code': 'sv08', 'cards': []},
  "Champion's Path": {'code': 'swsh3.5', 'cards': []},
  'Guardians Rising': { 'code': 'sm2',
                        'cards': [ { 'name': 'Sylveon GX',
                                     'market': 124.72,
                                     'price_high': 279.99,
                                     'printed_total': 145,
                                     'number': '158',
                                     'card_link': 'https://www.tcgplayer.com/product/131008',
                                     'pricecharting_url': 'https://pricecharting.com/game/pokemon-guardians-rising/sylveon-gx-158',
                                     'graded_prices': { 'ungraded': '$65.15',
                                                        'grade7': '$72.81',
                                                        'grade8': '$98.70',
                                                        'grade9': '$142.50',
                                                        'grade95': '$157.00',
                                                        'grade10': '$355.00'},
                                     'image_url': 'https://assets.tcgdex.net/en/sm/sm2/158/high.png'}]},
  'Burning Shadows': { 'code': 'sm3',
                       'cards': [ { 'name': 'Charizard GX',
                                    'market': 533.61,
                                    'price_high': 999.98,
                                    'printed_total': 147,
                                    'number': '150',
                                    'card_link': 'https://www.tcgplayer.com/product/138497',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-burning-shadows/charizard-gx-150',
                                    'graded_prices': { 'ungraded': '$301.33',
                                                       'grade7': '$310.00',
                                                       'grade8': '$400.00',
                                                       'grade9': '$602.50',
                                                       'grade95': '$1,452.00',
                                                       'grade10': '$4,463.81'},
                                    'image_url': 'https://assets.tcgdex.net/en/sm/sm3/150/high.png'}]},
  'Evolving Skies': { 'code': 'swsh7',
                      'cards': [ { 'name': 'Umbreon V',
                                   'market': 301.88,
                                   'price_high': 4321,
                                   'printed_total': 203,
                                   'number': '189',
                                   'card_link': 'https://www.tcgplayer.com/product/246719',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-evolving-skies/umbreon-v-189',
                                   'graded_prices': { 'ungraded': '$295.00',
                                                      'grade7': '$131.49',
                                                      'grade8': '$246.25',
                                                      'grade9': '$325.00',
                                                      'grade95': '$420.00',
                                                      'grade10': '$913.33'},
                                   'image_url': 'https://assets.tcgdex.net/en/swsh/swsh7/189/high.png'}]},
  'Forbidden Light': { 'code': 'sm6',
                       'cards': [ { 'name': 'Greninja GX',
                                    'market': 94.79,
                                    'price_high': 154.9,
                                    'printed_total': 131,
                                    'number': '133',
                                    'card_link': 'https://www.tcgplayer.com/product/165675',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-forbidden-light/greninja-gx-133',
                                    'graded_prices': { 'ungraded': '$66.25',
                                                       'grade7': '$45.00',
                                                       'grade8': '$56.33',
                                                       'grade9': '$108.75',
                                                       'grade95': '$120.00',
                                                       'grade10': '$382.91'},
                                    'image_url': 'https://assets.tcgdex.net/en/sm/sm6/133/high.png'},
                                  { 'name': 'Lucario GX',
                                    'market': 117.25,
                                    'price_high': 193.22,
                                    'printed_total': 131,
                                    'number': '135',
                                    'card_link': 'https://www.tcgplayer.com/product/165781',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-forbidden-light/lucario-gx-135',
                                    'graded_prices': { 'ungraded': '$78.52',
                                                       'grade7': '$35.00',
                                                       'grade8': '$60.50',
                                                       'grade9': '$111.80',
                                                       'grade95': '$129.99',
                                                       'grade10': '$389.33'},
                                    'image_url': 'https://assets.tcgdex.net/en/sm/sm6/135/high.png'}]},
  'Paldea Evolved': { 'code': 'sv2',
                      'cards': [ { 'name': 'Magikarp',
                                   'market': 274.66,
                                   'price_high': 1200.0,
                                   'printed_total': 193,
                                   'number': '203',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv2-203',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-paldea-evolved/magikarp-203',
                                   'graded_prices': { 'ungraded': '$259.99',
                                                      'grade7': '$237.50',
                                                      'grade8': '$242.50',
                                                      'grade9': '$341.53',
                                                      'grade95': '$670.00',
                                                      'grade10': '$2,330.00'},
                                   'image_url': 'https://images.pokemontcg.io/sv2/203_hires.png'}]},
  'Obsidian Flames': {'code': 'sv03', 'cards': []},
  'Dragon Majesty': { 'code': 'sm7.5',
                      'cards': [ { 'name': 'Ultra Necrozma GX',
                                   'market': 92.73,
                                   'price_high': 227,
                                   'printed_total': 70,
                                   'number': '78',
                                   'card_link': 'https://www.tcgplayer.com/product/175508',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-dragon-majesty/ultra-necrozma-gx-78',
                                   'graded_prices': { 'ungraded': '$77.68',
                                                      'grade7': '$24.36',
                                                      'grade8': '$81.10',
                                                      'grade9': '$108.16',
                                                      'grade95': '$112.00',
                                                      'grade10': '$360.00'},
                                   'image_url': ''}]},
  'Astral Radiance': {'code': 'swsh10', 'cards': []},
  'Vivid Voltage': {'code': 'swsh4', 'cards': []},
  'Paldean Fates': {'code': 'sv04.5', 'cards': []},
  'Journey Together': {'code': 'sv09', 'cards': []}}
