# Auto-generated file containing combined cards_info dictionary
cards_info = \
{ 'Silver Tempest': {'code': 'swsh12', 'cards': []},
  'Phantasmal Flames': { 'code': 'me2',
                         'cards': [ { 'name': 'Mega Charizard X ex',
                                      'market': 455.57,
                                      'price_high': 2222.0,
                                      'printed_total': 94,
                                      'number': '125',
                                      'card_link': 'https://prices.pokemontcg.io/tcgplayer/me2-125',
                                      'pricecharting_url': 'https://pricecharting.com/game/pokemon-phantasmal-flames/mega-charizard-x-ex-125',
                                      'graded_prices': { 'ungraded': '$562.35',
                                                         'grade7': '-',
                                                         'grade8': '$550.00',
                                                         'grade9': '$729.99',
                                                         'grade95': '$1,075.00',
                                                         'grade10': '$1,845.85'},
                                      'image_url': 'https://images.pokemontcg.io/me2/125_hires.png'},
                                    { 'name': 'Mega Charizard X ex',
                                      'market': 346.2,
                                      'price_high': 99999.0,
                                      'printed_total': 94,
                                      'number': '130',
                                      'card_link': 'https://prices.pokemontcg.io/tcgplayer/me2-130',
                                      'pricecharting_url': 'https://pricecharting.com/game/pokemon-phantasmal-flames/mega-charizard-x-ex-130',
                                      'graded_prices': { 'ungraded': '$363.33',
                                                         'grade7': '-',
                                                         'grade8': '$382.51',
                                                         'grade9': '$549.53',
                                                         'grade95': '$916.95',
                                                         'grade10': '$2,973.21'},
                                      'image_url': 'https://images.pokemontcg.io/me2/130_hires.png'}]},
  'Prismatic Evolutions': { 'code': 'sv8pt5',
                            'cards': [ { 'name': 'Ceruledge ex',
                                         'market': 101.05,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '147',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-147',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/ceruledge-ex-147',
                                         'graded_prices': { 'ungraded': '$88.50',
                                                            'grade7': '-',
                                                            'grade8': '$87.63',
                                                            'grade9': '$100.00',
                                                            'grade95': '$145.24',
                                                            'grade10': '$282.50'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/147_hires.png'},
                                       { 'name': 'Flareon ex',
                                         'market': 157.52,
                                         'price_high': 9999.0,
                                         'printed_total': 131,
                                         'number': '146',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-146',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/flareon-ex-146',
                                         'graded_prices': { 'ungraded': '$155.00',
                                                            'grade7': '-',
                                                            'grade8': '$149.75',
                                                            'grade9': '$151.06',
                                                            'grade95': '$155.75',
                                                            'grade10': '$550.00'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/146_hires.png'},
                                       { 'name': 'Jolteon ex',
                                         'market': 148.66,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '153',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-153',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/jolteon-ex-153',
                                         'graded_prices': { 'ungraded': '$131.25',
                                                            'grade7': '-',
                                                            'grade8': '$134.13',
                                                            'grade9': '$149.00',
                                                            'grade95': '$164.00',
                                                            'grade10': '$490.06'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/153_hires.png'},
                                       { 'name': 'Vaporeon ex',
                                         'market': 190.52,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '149',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-149',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/vaporeon-ex-149',
                                         'graded_prices': { 'ungraded': '$169.21',
                                                            'grade7': '$149.25',
                                                            'grade8': '$170.00',
                                                            'grade9': '$179.85',
                                                            'grade95': '$400.00',
                                                            'grade10': '$885.50'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/149_hires.png'},
                                       { 'name': 'Espeon ex',
                                         'market': 199.66,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '155',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-155',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/espeon-ex-155',
                                         'graded_prices': { 'ungraded': '$192.75',
                                                            'grade7': '$145.20',
                                                            'grade8': '$189.91',
                                                            'grade9': '$196.56',
                                                            'grade95': '$317.50',
                                                            'grade10': '$803.50'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/155_hires.png'},
                                       { 'name': 'Sylveon ex',
                                         'market': 314.13,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '156',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-156',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/sylveon-ex-156',
                                         'graded_prices': { 'ungraded': '$284.50',
                                                            'grade7': '$209.00',
                                                            'grade8': '$261.00',
                                                            'grade9': '$313.45',
                                                            'grade95': '$390.17',
                                                            'grade10': '$1,047.99'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/156_hires.png'},
                                       { 'name': 'Roaring Moon ex',
                                         'market': 173.01,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '162',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-162',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/roaring-moon-ex-162',
                                         'graded_prices': { 'ungraded': '$170.00',
                                                            'grade7': '-',
                                                            'grade8': '$165.82',
                                                            'grade9': '$166.50',
                                                            'grade95': '$316.25',
                                                            'grade10': '$659.00'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/162_hires.png'},
                                       { 'name': 'Umbreon ex',
                                         'market': 1069.35,
                                         'price_high': 5000.0,
                                         'printed_total': 131,
                                         'number': '161',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-161',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/umbreon-ex-161',
                                         'graded_prices': { 'ungraded': '$1,012.17',
                                                            'grade7': '$641.00',
                                                            'grade8': '$801.00',
                                                            'grade9': '$992.58',
                                                            'grade95': '$1,525.00',
                                                            'grade10': '$3,269.34'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/161_hires.png'},
                                       { 'name': 'Eevee ex',
                                         'market': 109.54,
                                         'price_high': 999.0,
                                         'printed_total': 131,
                                         'number': '167',
                                         'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8pt5-167',
                                         'pricecharting_url': 'https://pricecharting.com/game/pokemon-prismatic-evolutions/eevee-ex-167',
                                         'graded_prices': { 'ungraded': '$105.98',
                                                            'grade7': '-',
                                                            'grade8': '$91.50',
                                                            'grade9': '$118.31',
                                                            'grade95': '$180.54',
                                                            'grade10': '$501.27'},
                                         'image_url': 'https://images.pokemontcg.io/sv8pt5/167_hires.png'}]},
  'Black Bolt': { 'code': 'zsv10pt5',
                  'cards': [ { 'name': 'Seismitoad',
                               'market': 148.26,
                               'price_high': 450.0,
                               'printed_total': 86,
                               'number': '105',
                               'card_link': 'https://prices.pokemontcg.io/tcgplayer/zsv10pt5-105',
                               'pricecharting_url': 'https://pricecharting.com/game/pokemon-black-bolt/seismitoad-105',
                               'graded_prices': { 'ungraded': '$145.43',
                                                  'grade7': '$95.00',
                                                  'grade8': '$118.89',
                                                  'grade9': '$134.13',
                                                  'grade95': '$221.25',
                                                  'grade10': '$790.40'},
                               'image_url': 'https://images.pokemontcg.io/zsv10pt5/105_hires.png'}]},
  'Crown Zenith Galarian Gallery': {'code': 'swsh12pt5gg', 'cards': []},
  'Chilling Reign': {'code': 'swsh6', 'cards': []},
  'Twilight Masquerade': {'code': 'sv6', 'cards': []},
  'Lost Origin': { 'code': 'swsh11',
                   'cards': [ { 'name': 'Giratina V',
                                'market': 576.86,
                                'price_high': 899.0,
                                'printed_total': 196,
                                'number': '186',
                                'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh11-186',
                                'pricecharting_url': 'https://pricecharting.com/game/pokemon-lost-origin/giratina-v-186',
                                'graded_prices': { 'ungraded': '$525.00',
                                                   'grade7': '$427.63',
                                                   'grade8': '$537.76',
                                                   'grade9': '$615.00',
                                                   'grade95': '$1,208.87',
                                                   'grade10': '$1,794.18'},
                                'image_url': 'https://images.pokemontcg.io/swsh11/186_hires.png'}]},
  'Battle Styles': { 'code': 'swsh5',
                     'cards': [ { 'name': 'Tyranitar V',
                                  'market': 206.1,
                                  'price_high': 599.95,
                                  'printed_total': 163,
                                  'number': '155',
                                  'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh5-155',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-battle-styles/tyranitar-v-155',
                                  'graded_prices': { 'ungraded': '$197.50',
                                                     'grade7': '$90.21',
                                                     'grade8': '$177.55',
                                                     'grade9': '$206.85',
                                                     'grade95': '$321.37',
                                                     'grade10': '$655.38'},
                                  'image_url': 'https://images.pokemontcg.io/swsh5/155_hires.png'}]},
  'Mega Evolution': { 'code': 'me1',
                      'cards': [ { 'name': 'Mega Absol ex',
                                   'market': 81.02,
                                   'price_high': 999.0,
                                   'printed_total': 132,
                                   'number': '180',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/me1-180',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-absol-ex-180',
                                   'graded_prices': { 'ungraded': '$73.15',
                                                      'grade7': '-',
                                                      'grade8': '$101.20',
                                                      'grade9': '$111.00',
                                                      'grade95': '$122.00',
                                                      'grade10': '$251.09'},
                                   'image_url': 'https://images.pokemontcg.io/me1/180_hires.png'},
                                 { 'name': 'Mega Latias ex',
                                   'market': 85.28,
                                   'price_high': 999.0,
                                   'printed_total': 132,
                                   'number': '181',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/me1-181',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-mega-evolution/mega-latias-ex-181',
                                   'graded_prices': { 'ungraded': '$85.00',
                                                      'grade7': '-',
                                                      'grade8': '-',
                                                      'grade9': '$129.99',
                                                      'grade95': '$143.00',
                                                      'grade10': '$302.50'},
                                   'image_url': 'https://images.pokemontcg.io/me1/181_hires.png'}]},
  'Destined Rivals': { 'code': 'sv10',
                       'cards': [ { 'name': "Team Rocket's Mewtwo ex",
                                    'market': 402.5,
                                    'price_high': 9999.0,
                                    'printed_total': 182,
                                    'number': '231',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv10-231',
                                    'pricecharting_url': "https://pricecharting.com/game/pokemon-destined-rivals/team-rocket's-mewtwo-ex-231",
                                    'graded_prices': { 'ungraded': '$405.82',
                                                       'grade7': '$369.85',
                                                       'grade8': '$388.42',
                                                       'grade9': '$410.64',
                                                       'grade95': '$801.47',
                                                       'grade10': '$1,145.00'},
                                    'image_url': 'https://images.pokemontcg.io/sv10/231_hires.png'},
                                  { 'name': "Team Rocket's Nidoking ex",
                                    'market': 96.25,
                                    'price_high': 400.0,
                                    'printed_total': 182,
                                    'number': '233',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv10-233',
                                    'pricecharting_url': "https://pricecharting.com/game/pokemon-destined-rivals/team-rocket's-nidoking-ex-233",
                                    'graded_prices': { 'ungraded': '$100.00',
                                                       'grade7': '$76.00',
                                                       'grade8': '$95.06',
                                                       'grade9': '$116.51',
                                                       'grade95': '$128.00',
                                                       'grade10': '$271.90'},
                                    'image_url': 'https://images.pokemontcg.io/sv10/233_hires.png'}]},
  'Paradox Rift': {'code': 'sv4', 'cards': []},
  'Darkness Ablaze': {'code': 'swsh3', 'cards': []},
  '151': { 'code': 'sv3pt5',
           'cards': [ { 'name': 'Charizard ex',
                        'market': 251.97,
                        'price_high': 1000.0,
                        'printed_total': 165,
                        'number': '199',
                        'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv3pt5-199',
                        'pricecharting_url': 'https://pricecharting.com/game/pokemon-scarlet-&-violet-151/charizard-ex-199',
                        'graded_prices': { 'ungraded': '$234.50',
                                           'grade7': '$171.43',
                                           'grade8': '$217.55',
                                           'grade9': '$249.71',
                                           'grade95': '$365.50',
                                           'grade10': '$932.70'},
                        'image_url': 'https://images.pokemontcg.io/sv3pt5/199_hires.png'}]},
  'White Flare': {'code': 'rsv10pt5', 'cards': []},
  'Crown Zenith': {'code': 'swsh12pt5', 'cards': []},
  'Rebel Clash': {'code': 'swsh2', 'cards': []},
  'Fusion Strike': { 'code': 'swsh8',
                     'cards': [ { 'name': 'Mew V',
                                  'market': 88.77,
                                  'price_high': 500.0,
                                  'printed_total': 264,
                                  'number': '251',
                                  'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh8-251',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-fusion-strike/mew-v-251',
                                  'graded_prices': { 'ungraded': '$82.00',
                                                     'grade7': '$40.64',
                                                     'grade8': '$75.57',
                                                     'grade9': '$93.79',
                                                     'grade95': '$147.68',
                                                     'grade10': '$291.74'},
                                  'image_url': 'https://images.pokemontcg.io/swsh8/251_hires.png'}]},
  'Shining Fates': {'code': 'swsh45', 'cards': []},
  'Surging Sparks': { 'code': 'sv8',
                      'cards': [ { 'name': 'Milotic ex',
                                   'market': 96.46,
                                   'price_high': 199.95,
                                   'printed_total': 191,
                                   'number': '237',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8-237',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-surging-sparks/milotic-ex-237',
                                   'graded_prices': { 'ungraded': '$89.88',
                                                      'grade7': '$68.00',
                                                      'grade8': '$85.50',
                                                      'grade9': '$96.49',
                                                      'grade95': '$158.75',
                                                      'grade10': '$270.91'},
                                   'image_url': 'https://images.pokemontcg.io/sv8/237_hires.png'},
                                 { 'name': 'Pikachu ex',
                                   'market': 284.55,
                                   'price_high': 868.0,
                                   'printed_total': 191,
                                   'number': '238',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8-238',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-surging-sparks/pikachu-ex-238',
                                   'graded_prices': { 'ungraded': '$267.77',
                                                      'grade7': '$198.00',
                                                      'grade8': '$247.00',
                                                      'grade9': '$275.00',
                                                      'grade95': '$447.95',
                                                      'grade10': '$865.00'},
                                   'image_url': 'https://images.pokemontcg.io/sv8/238_hires.png'},
                                 { 'name': 'Latias ex',
                                   'market': 169.84,
                                   'price_high': 370.0,
                                   'printed_total': 191,
                                   'number': '239',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv8-239',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-surging-sparks/latias-ex-239',
                                   'graded_prices': { 'ungraded': '$151.90',
                                                      'grade7': '$123.00',
                                                      'grade8': '$153.61',
                                                      'grade9': '$169.00',
                                                      'grade95': '$240.68',
                                                      'grade10': '$547.00'},
                                   'image_url': 'https://images.pokemontcg.io/sv8/239_hires.png'}]},
  "Champion's Path": {'code': 'swsh35', 'cards': []},
  'Evolving Skies': {'code': 'swsh7', 'cards': []},
  'Paldea Evolved': { 'code': 'sv2',
                      'cards': [ { 'name': 'Magikarp',
                                   'market': 251.46,
                                   'price_high': 1200.0,
                                   'printed_total': 193,
                                   'number': '203',
                                   'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv2-203',
                                   'pricecharting_url': 'https://pricecharting.com/game/pokemon-paldea-evolved/magikarp-203',
                                   'graded_prices': { 'ungraded': '$224.40',
                                                      'grade7': '$185.00',
                                                      'grade8': '$221.52',
                                                      'grade9': '$285.00',
                                                      'grade95': '$710.14',
                                                      'grade10': '$1,798.82'},
                                   'image_url': 'https://images.pokemontcg.io/sv2/203_hires.png'}]},
  'Obsidian Flames': {'code': 'sv3', 'cards': []},
  'Astral Radiance': { 'code': 'swsh10',
                       'cards': [ { 'name': 'Starmie V',
                                    'market': 94.54,
                                    'price_high': 300.0,
                                    'printed_total': 30,
                                    'number': 'TG13',
                                    'card_link': 'https://prices.pokemontcg.io/tcgplayer/swsh10tg-TG13',
                                    'pricecharting_url': 'https://pricecharting.com/game/pokemon-astral-radiance/starmie-v-TG13',
                                    'graded_prices': { 'ungraded': '$94.81',
                                                       'grade7': '$77.02',
                                                       'grade8': '$89.00',
                                                       'grade9': '$99.45',
                                                       'grade95': '$128.09',
                                                       'grade10': '$280.00'},
                                    'image_url': 'https://images.pokemontcg.io/swsh10tg/TG13_hires.png'}]},
  'Vivid Voltage': {'code': 'swsh4', 'cards': []},
  'Paldean Fates': { 'code': 'sv4pt5',
                     'cards': [ { 'name': 'Mew ex',
                                  'market': 496.82,
                                  'price_high': 10000.0,
                                  'printed_total': 91,
                                  'number': '232',
                                  'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv4pt5-232',
                                  'pricecharting_url': 'https://pricecharting.com/game/pokemon-paldean-fates/mew-ex-232',
                                  'graded_prices': { 'ungraded': '$486.44',
                                                     'grade7': '$425.00',
                                                     'grade8': '$427.14',
                                                     'grade9': '$481.10',
                                                     'grade95': '$689.50',
                                                     'grade10': '$1,425.00'},
                                  'image_url': 'https://images.pokemontcg.io/sv4pt5/232_hires.png'}]},
  'Journey Together': { 'code': 'sv9',
                        'cards': [ { 'name': "Lillie's Clefairy ex",
                                     'market': 134.2,
                                     'price_high': 375.0,
                                     'printed_total': 159,
                                     'number': '184',
                                     'card_link': 'https://prices.pokemontcg.io/tcgplayer/sv9-184',
                                     'pricecharting_url': "https://pricecharting.com/game/pokemon-journey-together/lillie's-clefairy-ex-184",
                                     'graded_prices': { 'ungraded': '$128.00',
                                                        'grade7': '$123.88',
                                                        'grade8': '$128.45',
                                                        'grade9': '$139.99',
                                                        'grade95': '$194.85',
                                                        'grade10': '$444.00'},
                                     'image_url': 'https://images.pokemontcg.io/sv9/184_hires.png'}]}}
