# Generated by Django 5.1.6 on 2025-02-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0002_saveditems_delete_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditems',
            name='ebay_url',
            field=models.URLField(default='https://www.ebay.com/'),
        ),
        migrations.AddField(
            model_name='saveditems',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
