# Generated by Django 5.1.6 on 2025-02-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0003_saveditems_ebay_url_saveditems_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(default='https://example.com/default-image.jpg')),
                ('ebay_url', models.URLField(default='https://www.ebay.com/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedItems',
        ),
    ]
