# Generated by Django 5.1.6 on 2025-02-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0004_saveditem_delete_saveditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='grade10_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='grade8_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='grade95_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='grade9_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='time_left',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='ungraded_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
