# Generated by Django 5.1.6 on 2025-02-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0005_saveditem_grade10_price_saveditem_grade8_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveditem',
            name='grade8_price',
        ),
    ]
