# Generated by Django 5.1.6 on 2025-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0006_remove_saveditem_grade8_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='grade8_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
