# Generated by Django 5.1.6 on 2025-02-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0008_saveditem_grade7_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='grade10_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='grade7_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='grade8_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='grade95_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='grade9_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='ungraded_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
