# Generated by Django 5.1.6 on 2025-02-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0009_alter_saveditem_grade10_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=2056)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
