# Generated by Django 5.1.6 on 2025-02-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0010_ebayapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayapikey',
            name='api_key',
            field=models.CharField(max_length=3000),
        ),
    ]
