# Generated by Django 5.1.6 on 2025-02-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0011_alter_ebayapikey_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebayapikey',
            options={'verbose_name': 'eBay API Key', 'verbose_name_plural': 'eBay API Keys'},
        ),
    ]
