# Generated by Django 4.2.9 on 2025-03-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0012_alter_ebayapikey_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayapikey',
            name='time_updated',
        ),
    ]
