# Generated by Django 4.2.9 on 2025-03-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0013_remove_ebayapikey_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='time_date_ending',
            field=models.DateTimeField(null=True),
        ),
    ]
