# Generated by Django 4.2.9 on 2025-03-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0014_saveditem_time_date_ending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveditem',
            old_name='time_date_ending',
            new_name='end_time',
        ),
    ]
