# Generated by Django 4.2.9 on 2025-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0015_rename_time_date_ending_saveditem_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='sold_url',
            field=models.URLField(default='https://www.ebay.com/'),
        ),
    ]
