# Generated by Django 4.2.9 on 2025-03-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0016_saveditem_sold_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Search Exclusion',
                'verbose_name_plural': 'Search Exclusions',
            },
        ),
    ]
