# Generated by Django 4.2.9 on 2025-03-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0018_alter_searchexclusion_exclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchexclusion',
            name='exclusion',
            field=models.CharField(max_length=255),
        ),
    ]
