# Generated by Django 4.2.9 on 2025-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_ebay_tracker', '0022_alter_searchexclusion_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='buy_it_now_url',
            field=models.URLField(default='https://www.ebay.com/'),
        ),
    ]
