name: Combine PSA JSON

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.POKEMON_PAT_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python scripts/combine_json.py

      - name: Commit and push changes
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --no-rebase || echo "Pull failed, continuing"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Add Combined PSA File"
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Trigger Update Website workflow
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.POKEMON_PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "update-website.yaml",
              ref: "main"
            })
