name: Combine PSA JSON

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python script
        run: |
          python scripts/combine_json.py

      - name: Commit and push changes
        run: |
          git pull
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Add Combined PSA File"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
