name: Generate PSA JSON

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      max-parallel: 4
      matrix:
        set:
          # Uncomment sets as needed
          # - "Sword & Shield"
          # - "Rebel Clash"
          # - "Darkness Ablaze"
          # - "Champion's Path"
          # - "Vivid Voltage"
          # - "Shining Fates"
          # - "Battle Styles"
          # - "Chilling Reign"
          # - "Evolving Skies"
          # - "Fusion Strike"
          # - "Brilliant Stars"
          # - "Astral Radiance"
          # - "Lost Origin"
          # - "Silver Tempest"
          # - "Paradox Rift"
          # - "Paldean Fates"
          # - "Twilight Masquerade"
          # - "Brilliant Stars"
          # - "Astral Radiance"
          # - "Silver Tempest"
          # - "Vivid Voltage"
          # - "Obsidian Flames"
          # - "151"
          # - "Paldea Evolved"
          # - "Crown Zenith Galarian Gallery"
          # - "Evolving Skies"
          # - "Crown Zenith"
          # - "Surging Sparks"
          # - "Prismatic Evolutions"
          # - "Journey Together"
          # - "Destined Rivals"
          - "Black Bolt"
          - "White Flare"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python script
        run: |
          python generate_psa_json.py "${{ matrix.set }}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update PSA JSON for ${{ matrix.set }}" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
