name: Update Website

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Assume role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::870927831149:role/kortiz-github-repository
          role-session-name: GitHubActionsSession
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations (if needed)
        working-directory: ./django/pokemon_tracker_project
        run: |
          python manage.py migrate || echo "No migrations needed"

      - name: Collect static files (optional)
        working-directory: ./django/pokemon_tracker_project
        run: |
          python manage.py collectstatic --noinput || echo "No static files"

      - name: Start Django server in background
        working-directory: ./django/pokemon_tracker_project
        run: |
          nohup python manage.py runserver 127.0.0.1:8000 &
          sleep 5  # wait for the server to start

      - name: Curl index.html
        run: |
          curl -s http://127.0.0.1:8000/psa_tracker > rendered_index.html

      - name: Commit rendered index.html
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add rendered_index.html
          git commit -m "Auto-generated index.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to S3
        run: |
          aws s3 cp rendered_index.html s3://psa.kevs-pokemon-tracker.com/index.html
